### ISSUE TITLE
Amélioration wiki

### ISSUE THREAD

**Issue by moussadiallo** [emmanuelndong/Developpement-d-un-site-web-pour-les-scouts-du-senegal#1]
Très belle initiative, faire tout pour que cela aboutisse.
Améliorer le wiki en mettant des photos de scout, décrire leur activités .......

**Comment by emmanuelndong** [comment]
![scoutsn](https://user-images.githubusercontent.com/34041179/35403112-9b8037de-01f6-11e8-88d0-d37fae2422e8.png)
![18922216_812869188870428_660299250318190787_n](https://user-images.githubusercontent.com/34041179/35403196-e7a02408-01f6-11e8-8b33-f52e84a8e387.jpg)
![18922218_814125315411482_532471162534692393_n](https://user-images.githubusercontent.com/34041179/35403216-fa7f4874-01f6-11e8-828c-94f1c7d2de59.jpg)
![18921659_812869058870441_6219855629735007201_n](https://user-images.githubusercontent.com/34041179/35403218-fc163166-01f6-11e8-92dc-06f7868c2a50.jpg)

**Comment by emmanuelndong** [comment]
c'est fait
